export { xorshift128, type Rng } from './prng';
export { fnv1a, dailySeed, currentRideDate } from './seed';
export {
  UNIT_DEFS,
  TEST_HORDE,
  tierAttackMultiplier,
  tierHealthMultiplier,
  reviveHpForTier,
  blockHitsForTier,
  wardArmorForTier,
  poisonStacksForTier,
  cellarCoilChargeCapForTier,
  backlineTargetsForTier,
  buffSummonedForTier,
  poisonResistForTier,
  POISON_RESIST_CAP,
  type UnitDef,
  type Ability,
  type Effect,
  type Side,
  type Lineup,
  type LineupUnit,
  type TimeOfDay,
} from './data/units';
export {
  KEYWORD_FAMILIES,
  FAMILY_COLOR,
  FAMILY_TEXT_COLOR,
  FAMILY_TEXT_ON,
  FAMILY_TEXT_MIN_CONTRAST,
  FAMILY_GLYPH,
  EFFECT_FAMILY,
  EFFECT_KEYWORD,
  unitKeyword,
  relicKeyword,
  keywordFamily,
  type KeywordFamily,
  type UnitKeyword,
} from './data/keyword-family';
export { RELIC_DEFS, type RelicDef } from './data/relics';
export { ENEMY_POOL } from './data/enemies';
export type { Archetype } from './data/units';
export {
  generateGauntlet,
  difficultyForDay,
  type Gauntlet,
  type GauntletTheme,
  type EnemyWave,
  WAVE_COUNT,
} from './gauntlet';
export {
  anomalyFor,
  ANOMALY_DEFS,
  ANOMALY_FIRST_SEASON,
  type AnomalyDef,
  type GauntletOverrides,
  type ShopOverrides,
} from './anomaly';
export { scoutReport, ARCHETYPE_LABEL, type ScoutReport, type ScoutHint } from './scout';
export {
  newBuild,
  advanceAfterDawn,
  boardCapForDay,
  combatCapForBuild,
  effectiveBoardCap,
  buyBoardSlot,
  nextSlotPrice,
  SLOT_PRICES,
  weekdayFor,
  seasonIdFor,
  SEASON_DAYS,
  SCRAP_PER_DEPTH,
  scrapForDepth,
  rollOfferings,
  upcomingUnlocks,
  upcomingRetirements,
  shopUnitPoolForDay,
  seasonUnitPool,
  seasonRelicPool,
  buyUnit,
  canRecruit,
  buyRelic,
  hasValidRelicTarget,
  sellUnit,
  sellBenchUnit,
  sellRefund,
  rerollShop,
  autoRerollShop,
  isShopDead,
  toggleFreeze,
  moveUnit,
  benchUnit,
  deployUnit,
  swapWithBench,
  lineupFromBuild,
  unitStats,
  DAILY_SCRAP,
  REROLL_COST,
  MAX_TIER,
  BENCH_SIZE,
  type BuildState,
  type BoardUnit,
  type ShopSlot,
  type ActionResult,
} from './shop';
export {
  simulate,
  simulateCore,
  BOARD_CAP,
  COMBAT_CAP_BONUS,
  MIN_ATTACK_DAMAGE,
  SCORE_PER_WAVE,
  ENEMY_HEALTH_SCALE_PER_WAVE,
  ENEMY_HEALTH_SCALE_QUADRATIC,
  ENEMY_ATTACK_SCALE_PER_WAVE,
  enemyHealthScale,
  enemyAttackScale,
  type BattleEvent,
  type BattleResult,
  type BattleMode,
  type CoreOutput,
  type UnitView,
} from './sim';
export { simulateDuel, type DuelResult } from './duel';
export {
  scoreRound,
  validateBoard,
  legalEntrants,
  consolationScrap,
  scoutSummary,
  LOSS_CONSOLATION_DEFAULT,
  type LeagueEntrant,
  type RoundStanding,
  type ScoutSummary,
} from './pvp';
